#!/bin/bash

set -eu

tools_path=$(dirname "$0")
# Path of the `dandi-schema` repo
dandi_schema_path="${tools_path}"/..
# Path of the `schema` repo
schemata_path=${1:-.}

LIBRARY_VERSION="$(git -C "${dandi_schema_path}" describe --tags --exact-match)"
SCHEMA_VERSION="$("$tools_path"/get-schema-version)"

git -C "$schemata_path" add releases

if ! git -C "$schemata_path" diff --quiet --cached
then
    # Publish/release a new schema to the `schema` repo
    git -C "$schemata_path" commit -m "Publish model schema v$SCHEMA_VERSION as of dandischema v$LIBRARY_VERSION"
    git -C "$schemata_path" push
    
    # Tag the `dandi-schema` repo with the new schema version
    git -C "$dandi_schema_path" tag -m "Schema v$SCHEMA_VERSION, released in dandischema v$LIBRARY_VERSION" "schema-$SCHEMA_VERSION"
    git -C "$dandi_schema_path" push --tags
else
    echo "No changes to commit"
fi
