#!/usr/bin/env python3

import re
import sys

from dandischema.consts import DANDI_SCHEMA_VERSION

if not re.match(r"[0-9]+\.[0-9]+\.[0-9]+$", DANDI_SCHEMA_VERSION):
    sys.stderr.write(f"[ERROR] Invalid schema version: '{DANDI_SCHEMA_VERSION}'\n")
    sys.exit(1)

print(DANDI_SCHEMA_VERSION)
