# Remove all `notes` entries containing the "Impossible to generate slot usage
# entry for the schemaKey" message generated by pydantic2linkml from YAML content.
# Reads from stdin, writes to stdout.

import sys

from ruamel.yaml import YAML

PATTERN = "pydantic2linkml: Impossible to generate slot usage entry for the schemaKey"


def process(obj):
    if isinstance(obj, dict):
        if "notes" in obj:
            to_remove = [i for i, note in enumerate(obj["notes"]) if PATTERN in note]
            for i in reversed(to_remove):
                del obj["notes"][i]
            if not obj["notes"]:
                del obj["notes"]
        for value in obj.values():
            process(value)
    elif isinstance(obj, list):
        for item in obj:
            process(item)


try:
    yaml = YAML()
    yaml.preserve_quotes = True
    data = yaml.load(sys.stdin)
    process(data)
    yaml.dump(data, sys.stdout)
    print("remove_impossible_slot_usage_notes: done", file=sys.stderr)
except Exception as e:
    print(f"remove_impossible_slot_usage_notes: failed — {e}", file=sys.stderr)
    sys.exit(1)
