name: Test against dandi-cli

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  test-dandi-cli:
    runs-on: ${{ matrix.os }}
    env:
      NO_ET: 1
      DANDI_TESTS_PULL_DOCKER_COMPOSE: 0
    strategy:
      fail-fast: false
      matrix:
        # Default matrix: dandischema installed only into client, across
        # all OSes and both released and master versions of dandi-cli.
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        python:
          - '3.11'
        version:
          - master
          - release
        schema_install:
          - client
        vendored_dandiapi:
          # Allow vendor information for the dandi-api instance to default to
          #   the default values specified in
          #   dandi/tests/data/dandiarchive-docker/docker-compose.yml of the
          #   dandi-cli repo.
          - default
        include:
          # dandischema installed only into the server (master dandi-cli only,
          # Ubuntu only since Docker is required)
          - os: ubuntu-latest
            python: '3.11'
            version: master
            schema_install: server
            vendored_dandiapi: default
          # dandischema installed into both client and server (both masters)
          - os: ubuntu-latest
            python: '3.11'
            version: master
            schema_install: both
            vendored_dandiapi: default
          # Vendorized (ember-dandi) with dandischema in both client and server
          - os: ubuntu-latest
            python: '3.11'
            version: master
            schema_install: both
            vendored_dandiapi: ember-dandi
            instance_name: EMBER-DANDI
            instance_identifier: 'RRID:SCR_026700'
            doi_prefix: '10.82754'
    steps:
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Update pip & install wheel
        run: python -m pip install --upgrade pip wheel

      - name: Install master branch of dandi
        if: matrix.version == 'master'
        run: pip install "dandi[test,extras] @ git+https://github.com/dandi/dandi-cli.git"

      - name: Install latest release of dandi
        if: matrix.version == 'release'
        run: pip install "dandi[test,extras]"

      - name: Check out dandischema
        uses: actions/checkout@v6
        with:
          # Fetch all commits so that versioningit will return something
          # compatible with semantic-version
          fetch-depth: 0
          path: dandischema

      - name: Install dandischema into client
        if: matrix.schema_install != 'server'
        run: pip install .
        working-directory: dandischema

      - name: Build dandi-api image with this version of dandischema
        if: matrix.schema_install != 'client'
        run: |
          docker build \
            -t dandiarchive/dandiarchive-api \
            -f tools/api-with-schema.Dockerfile \
            .
        working-directory: dandischema

      # Set only if matrix.instance_name is defined
      - name: Set DANDI_TESTS_INSTANCE_NAME
        if: ${{ matrix.instance_name }}
        run: echo "DANDI_TESTS_INSTANCE_NAME=${{ matrix.instance_name }}" >> "$GITHUB_ENV"

      # Set only if matrix.instance_identifier is defined
      - name: Set DANDI_TESTS_INSTANCE_IDENTIFIER
        if: ${{ matrix.instance_identifier }}
        run: echo "DANDI_TESTS_INSTANCE_IDENTIFIER=${{ matrix.instance_identifier }}" >> "$GITHUB_ENV"

      # Set only if matrix.doi_prefix is defined
      - name: Set DANDI_TESTS_DOI_PREFIX
        if: ${{ matrix.doi_prefix }}
        run: echo "DANDI_TESTS_DOI_PREFIX=${{ matrix.doi_prefix }}" >> "$GITHUB_ENV"

      - name: Run dandi-cli tests
        run: python -m pytest -s -v --pyargs dandi
